[package]
name = "packtool"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "packtool"
path = "src/main.rs"


[dependencies]
wasm-bindgen = "0.2.59"
glob = "0.3.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tempfile = "3.10.1"
clap = "4.5.4"
